Revert "Use pyproject.toml for py versions in ci"
This reverts commit 1ea7af6ffe3e76dd9d63cbf136fbb6f7d3bbdf7a.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,6 +2,10 @@ name: ci
 
 on: [push, pull_request]
 
+env:
+  X_PYTHON_MIN_VERSION: "3.9"
+  X_PYTHON_MAX_VERSION: "3.12"
+
 jobs:
   check-python-versions:
     # This job checks that the Python Versions we support match and are not End of Life
@@ -11,23 +15,35 @@ jobs:
         working-directory: ./etc/scripts
     steps:
       - uses: actions/checkout@v2
-      - name: Set up Python
-        uses: actions/setup-python@v5
+      - name: Set up Python ${{ env.X_PYTHON_MIN_VERSION }}
+        uses: actions/setup-python@v2
         with:
-          python-version-file: 'sdk/pyproject.toml'
+          python-version: ${{ env.X_PYTHON_MIN_VERSION }}
       - name: Install Python dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r ./check_python_versions_requirements.txt
       - name: Check Supported Python Versions
         run: |
-          python check_python_versions_supported.py
+          python check_python_versions_supported.py \
+            ${{ env.X_PYTHON_MIN_VERSION }} \
+            ${{ env.X_PYTHON_MAX_VERSION }}
+
+      - name: Check Python Versions coincide with the SDKs pyproject.toml
+        run: |
+          python check_python_versions_coincide.py \
+            ../../sdk/pyproject.toml \
+            ${{ env.X_PYTHON_MIN_VERSION }} \
+            ${{ env.X_PYTHON_MAX_VERSION }}
 
       # Todo: Check other pyproject.toml here as well, as we add them
 
   sdk-test:
     # This job runs the unittests on the python versions specified down at the matrix
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: ["3.9", "3.12"]
     env:
       COUCHDB_ADMIN_PASSWORD: "yo0Quai3"
       # (2024-10-11, s-heppner)
@@ -49,10 +65,16 @@ jobs:
         working-directory: ./sdk
     steps:
     - uses: actions/checkout@v2
-    - name: Set up Python
-      uses: actions/setup-python@v5
+    - name: Verify Matrix Version matches Global Version
+      run: |
+        if [ "${{ matrix.python-version }}" != "${{ env.X_PYTHON_MIN_VERSION }}" ] && [ "${{ matrix.python-version }}" != "${{ env.X_PYTHON_MAX_VERSION }}" ]; then
+          echo "Error: Matrix version ${{ matrix.python-version }} does not match global version."
+          exit 1
+        fi
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v2
       with:
-        python-version-file: 'sdk/pyproject.toml'
+        python-version: ${{ matrix.python-version }}
     - name: Collect schema files from aas-specs
       run: |
         mkdir -p ./test/adapter/schema
@@ -81,10 +103,10 @@ jobs:
         working-directory: ./sdk
     steps:
     - uses: actions/checkout@v2
-    - name: Set up Python
-      uses: actions/setup-python@v5
+    - name: Set up Python ${{ env.X_PYTHON_MIN_VERSION }}
+      uses: actions/setup-python@v2
       with:
-        python-version-file: 'sdk/pyproject.toml'
+        python-version: ${{ env.X_PYTHON_MIN_VERSION }}
     - name: Install Python dependencies
       run: |
         python -m pip install --upgrade pip
@@ -104,10 +126,10 @@ jobs:
         working-directory: ./sdk
     steps:
     - uses: actions/checkout@v2
-    - name: Set up Python
-      uses: actions/setup-python@v5
+    - name: Set up Python ${{ env.X_PYTHON_MIN_VERSION }}
+      uses: actions/setup-python@v2
       with:
-        python-version-file: 'sdk/pyproject.toml'
+        python-version: ${{ env.X_PYTHON_MIN_VERSION }}
     - name: Install Python dependencies
       run: |
         python -m pip install --upgrade pip
@@ -130,10 +152,10 @@ jobs:
         working-directory: ./sdk
     steps:
     - uses: actions/checkout@v2
-    - name: Set up Python
-      uses: actions/setup-python@v5
+    - name: Set up Python ${{ env.X_PYTHON_MIN_VERSION }}
+      uses: actions/setup-python@v2
       with:
-        python-version-file: 'sdk/pyproject.toml'
+        python-version: ${{ env.X_PYTHON_MIN_VERSION }}
     - name: Install Python dependencies
       run: |
         python -m pip install --upgrade pip
@@ -151,10 +173,10 @@ jobs:
         working-directory: ./sdk
     steps:
     - uses: actions/checkout@v2
-    - name: Set up Python
-      uses: actions/setup-python@v5
+    - name: Set up Python ${{ env.X_PYTHON_MIN_VERSION }}
+      uses: actions/setup-python@v2
       with:
-        python-version-file: 'sdk/pyproject.toml'
+        python-version: ${{ env.X_PYTHON_MIN_VERSION }}
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
